version: '3'
services:

  nginx:
    container_name: nginx
    image: nginx:mainline-alpine
    ports:
      - "80:80"
    volumes:
       - ./app:/app
       - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    links:
       - app

  app:
    container_name: app
    image: php:7-fpm
    volumes:
      - ./app:/app
    environment:
      DB_NAME: mydb
      DB_USER: root
      DB_PASSWORD: mypw
      DB_HOST: mysql
    links:
      - mysql

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mypw
      MYSQL_DATABASE: db-tugas5
    volumes:
      - db-tugas5:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
volumes:
  db-tugas5: